import {useState} from 'react';
import {Link} from 'react-router-dom';
export default function AcceptInvite(){
 const [token]=useState(()=>window.location.hash.slice(1));

 const [password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState(''),[username,setUsername]=useState(''),[busy,setBusy]=useState(false);
 const submit=async(e:any)=>{e.preventDefault();setError('');if(password!==confirmation){setError('As senhas devem ser iguais.');return;}setBusy(true);try{const r=await fetch('/api/accounts/accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password})});const data=await r.json();if(!r.ok)throw Error(data.error || 'Convite indisponível.');setUsername(data.username);window.history.replaceState(null,'',window.location.pathname);setPassword('');setConfirmation('');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <main className="admin-page min-h-screen bg-slate-950 text-slate-100 p-5 max-w-xl mx-auto space-y-5"><h1 className="text-3xl font-bold">Seu acesso ao LB Performance</h1>{username?<section className="bg-white text-slate-900 p-5 rounded-xl space-y-4"><h2 className="text-xl font-bold">Senha definida</h2><p>Seu usuário é <strong>{username}</strong>. Entre com ele e a senha que você acabou de criar.</p><Link to="/hub" className="inline-block bg-green-700 text-white px-5 py-3 rounded font-semibold">Entrar no aplicativo</Link></section>:! /^[a-f0-9]{64}$/.test(token)?<><p>Abra o link completo recebido do seu treinador. Se ele expirou, solicite um novo convite.</p><Link to="/hub" className="text-green-400">Voltar ao login</Link></>:<form onSubmit={submit} className="bg-slate-800 border border-slate-600 rounded-xl p-5 space-y-4"><p>Crie uma senha com pelo menos 8 caracteres. Este convite só pode ser usado uma vez.</p><label className="block">Sua senha<input type="password" required minLength={8} maxLength={72} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="admin-field w-full"/></label><label className="block">Confirme a senha<input type="password" required minLength={8} maxLength={72} autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="admin-field w-full"/></label>{error&&<p role="alert" className="bg-red-100 text-red-900 p-3 rounded">{error}</p>}<button disabled={busy} className="bg-green-600 text-white px-5 py-3 rounded font-semibold disabled:opacity-50">{busy?'Definindo senha…':'Definir senha e ativar acesso'}</button></form>}</main>;
}
