import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import type {UserWithPlan} from '../utils/plan';
const statusNames:Record<string,string>={pending:'Pendente',accepted:'Aceito',revoked:'Revogado',expired:'Expirado'};
export default function AccessSettings({user}:{user:UserWithPlan}){
 const [params]=useSearchParams();const requestedAthlete=params.get('athlete') || '';
 const [organizations,setOrganizations]=useState<any[]>([]),[organizationId,setOrganizationId]=useState(user.organizationId || ''),[athletes,setAthletes]=useState<any[]>([]),[athleteId,setAthleteId]=useState(requestedAthlete),[role,setRole]=useState('athlete'),[username,setUsername]=useState(''),[invites,setInvites]=useState<any[]>([]),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[created,setCreated]=useState<any>(null),[newOrgName,setNewOrgName]=useState('');
 const api=async(path:string,init:RequestInit={})=>{const r=await fetch('/api/accounts/'+path,{...init,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${user.token}`}});const data=await r.json();if(r.status===401)window.dispatchEvent(new Event('lb:session-invalid'));if(!r.ok)throw Error(data.error || 'Não foi possível concluir.');return data;};
 const loadInvites=async()=>{const data=await api(`access/invites?organizationId=${organizationId}&page=${page}`);setInvites(data.items);setHasMore(data.hasMore);};
 useEffect(()=>{let alive=true;api('access/organizations').then(data=>{if(!alive)return;setOrganizations(data);setOrganizationId(current=>data.some((o:any)=>o.id===current)?current:data[0]?.id || '');}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[user.token]);
 useEffect(()=>{let alive=true;setAthletes([]);setAthleteId('');setUsername('');setCreated(null);setError('');setMessage('');if(!organizationId)return;setLoading(true);api(`access/athletes?organizationId=${organizationId}`).then(data=>{if(!alive)return;setAthletes(data);const selected=data.find((a:any)=>a.id===requestedAthlete);if(selected){setAthleteId(selected.id);setUsername(selected.login_username || suggestUsername(selected.name));}}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[organizationId,user.token,requestedAthlete]);
 useEffect(()=>{let alive=true;setInvites([]);setHasMore(false);if(organizationId)api(`access/invites?organizationId=${organizationId}&page=${page}`).then(data=>{if(alive){setInvites(data.items);setHasMore(data.hasMore);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[organizationId,page,user.token]);
 function suggestUsername(name:string){return name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'.').replace(/^\.|\.$/g,'').slice(0,100);}
 const chooseAthlete=(id:string)=>{setAthleteId(id);const a=athletes.find(a=>a.id===id);setUsername(a?a.login_username || suggestUsername(a.name):'');};
 const create=async(body:any)=>{const data=await api('invites',{method:'POST',body:JSON.stringify(body)});setCreated({...data,username:body.username,url:`${window.location.origin}/convite#${data.token}`});setMessage('Convite gerado. Copie o link ou compartilhe com a pessoa.');await loadInvites();};
 const submit=async(e:any)=>{e.preventDefault();setBusy(true);setError('');setCreated(null);try{await create({organizationId,role,username:username.trim(),athleteId:role==='athlete'?athleteId:null});}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const revoke=async(invite:any)=>{if(!window.confirm(`Revogar o convite de ${invite.username}? O link deixará de funcionar.`))return;setBusy(true);setError('');try{await api(`access/invites/${invite.id}`,{method:'DELETE'});setCreated(null);setMessage('Convite revogado.');await loadInvites();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const resend=async(invite:any)=>{if(invite.status==='pending' && !window.confirm('O link anterior será revogado. Deseja gerar um novo convite?'))return;setBusy(true);setError('');setCreated(null);let revoked=false;try{if(invite.status==='pending'){await api(`access/invites/${invite.id}`,{method:'DELETE'});revoked=true;}await create({organizationId,role:invite.role,username:invite.username,athleteId:invite.athlete_id});}catch(e:any){setError((revoked?'O link anterior foi revogado. ':'')+e.message);await loadInvites().catch(()=>{});}finally{setBusy(false);}};
 const createOrganization=async(e:any)=>{e.preventDefault();setBusy(true);setError('');try{const org=await api('organizations',{method:'POST',body:JSON.stringify({name:newOrgName})});setOrganizations(prev=>[...prev,org]);setOrganizationId(org.id);setPage(0);setRole('coach');setNewOrgName('');setMessage('Organização criada e vinculada à supervisão. Defina o usuário do treinador e gere o convite.');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const share=created?`Você recebeu um convite para o LB Performance. Usuário: ${created.username}. Defina sua senha no link: ${created.url} O convite vale por 48 horas.`:'';
 return <main className="admin-page min-h-screen max-w-5xl mx-auto bg-slate-950 text-slate-100 p-4 sm:p-6 space-y-5"><Link to="/hub" className="text-green-400 font-semibold">← Voltar ao aplicativo</Link><h1 className="text-3xl font-bold">Configurações — Acessos e convites</h1><p>Cadastre o atleta no aplicativo e selecione seu nome para criar o acesso. O convite define a senha; o aluno entra depois com usuário e senha.</p>{error&&<p role="alert" className="bg-red-100 text-red-900 p-4 rounded">{error}</p>}{message&&<p role="status" className="bg-green-100 text-green-900 p-4 rounded">{message}</p>}
 <label className="block font-semibold">Organização<select className="admin-field w-full" value={organizationId} disabled={busy} onChange={e=>{setOrganizationId(e.target.value);setPage(0);}}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 {user.platformAdmin&&<details className="bg-slate-800 p-5 rounded border border-slate-600"><summary className="font-semibold cursor-pointer">Criar organização de um novo treinador</summary><form onSubmit={createOrganization} className="mt-4 space-y-3"><label className="block">Nome da organização<input required maxLength={100} value={newOrgName} onChange={e=>setNewOrgName(e.target.value)} className="admin-field w-full"/></label><button className="bg-green-600 px-5 py-3 rounded font-semibold" disabled={busy}>Criar organização</button></form></details>}
 <form onSubmit={submit} className="bg-slate-800 p-5 rounded-xl border border-slate-600 space-y-4"><h2 className="text-xl font-bold">Convidar ou redefinir acesso</h2>{user.platformAdmin&&<label className="block">Perfil<select className="admin-field w-full" value={role} onChange={e=>{setRole(e.target.value);setUsername('');}}><option value="athlete">Aluno</option><option value="coach">Treinador</option></select></label>}{role==='athlete'&&<label className="block">Atleta<select required className="admin-field w-full" value={athleteId} onChange={e=>chooseAthlete(e.target.value)}><option value="">{loading?'Carregando…':'Selecione o atleta cadastrado'}</option>{athletes.map(a=><option key={a.id} value={a.id}>{a.name}{a.login_username?' — usuário cadastrado':''}</option>)}</select></label>}<label className="block">Usuário de acesso<input required className="admin-field w-full" value={username} onChange={e=>setUsername(e.target.value)} minLength={3} maxLength={100} pattern="[a-zA-Z0-9._@-]{3,100}" placeholder="Ex.: joao.silva"/></label><p className="text-sm">Use letras sem acentos, números, ponto, hífen ou @. Para redefinir a senha, use o usuário já existente.</p><button disabled={busy||!organizationId||loading} className="bg-green-600 text-white px-5 py-3 rounded font-semibold disabled:opacity-50">Gerar convite</button>{!loading&&role==='athlete'&&!athletes.length&&<p>Esta organização ainda não tem atletas. Cadastre o atleta no aplicativo e volte aqui.</p>}</form>
 {created&&<section className="bg-white text-slate-900 border border-slate-300 p-5 rounded-xl space-y-3"><h2 className="font-bold text-xl">Compartilhar convite — {created.username}</h2><p>Expira em {new Date(created.expires_at).toLocaleString('pt-BR')}. O link só pode ser usado uma vez.</p><input readOnly className="admin-field w-full" value={created.url} aria-label="Link do convite" onFocus={e=>e.target.select()}/><div className="flex flex-wrap gap-3"><button onClick={async()=>{try{await navigator.clipboard.writeText(share);setMessage('Convite copiado.');}catch{setMessage('Selecione e copie o link acima.');}}} className="bg-green-700 text-white px-5 py-3 rounded font-semibold">Copiar convite</button><a href={`https://wa.me/?text=${encodeURIComponent(share)}`} target="_blank" rel="noopener noreferrer" className="bg-green-700 text-white px-5 py-3 rounded font-semibold">Compartilhar pelo WhatsApp</a></div></section>}
 <section className="bg-slate-800 border border-slate-600 p-5 rounded-xl space-y-4"><h2 className="text-xl font-bold">Histórico de convites</h2>{!invites.length&&<p>Nenhum convite nesta página.</p>}{invites.map(invite=><article key={invite.id} className="border-b border-slate-600 pb-4 space-y-2"><strong>{invite.username} — {invite.role==='coach'?'Treinador':invite.athlete_name || 'Aluno'}</strong><p>{statusNames[invite.status]} · Validade: {new Date(invite.expires_at).toLocaleString('pt-BR')}</p><div className="flex flex-wrap gap-3">{invite.status==='pending'&&<button disabled={busy} onClick={()=>revoke(invite)} className="bg-slate-600 text-white px-4 py-3 rounded">Revogar</button>}<button disabled={busy} onClick={()=>resend(invite)} className="bg-green-600 text-white px-4 py-3 rounded">{invite.status==='accepted'?'Redefinir acesso':'Gerar novo convite'}</button></div></article>)}<div className="flex gap-3 items-center"><button disabled={!page||busy} onClick={()=>setPage(p=>p-1)} className="bg-green-600 px-4 py-3 rounded disabled:opacity-40">Anterior</button><span>Página {page+1}</span><button disabled={!hasMore||busy} onClick={()=>setPage(p=>p+1)} className="bg-green-600 px-4 py-3 rounded disabled:opacity-40">Próxima</button></div></section>
 </main>;
}
