import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import type { UserWithPlan } from '../utils/plan';
export default function AccountSetup({onAuthenticated}:{onAuthenticated:(user:UserWithPlan)=>void}) {
 const [inviteRole,setInviteRole]=useState('coach');const [token,setToken]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 const call=async(e:React.FormEvent<HTMLFormElement>,path:string)=>{
  e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;
  const body=Object.fromEntries(new FormData(form));
  try{const response=await fetch(`/api/accounts/${path}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const data=await response.json();if(!response.ok) throw Error(data.error);if(path==='login'){if(!data.platformAdmin) throw Error('Esta área é reservada à administração.');setToken(data.token);onAuthenticated(data);setMessage('Administração autenticada. Use Voltar para acessar seus atletas.');}else if(path==='setup-admin'){setMessage('Administração configurada. Entre com sua nova senha.');form.reset();}else if(path==='accept'){setMessage('Senha definida. Entre no aplicativo; o acesso depende da assinatura vinculada.');form.reset();}else if(path==='organizations') setMessage(`Organização criada: ${data.id}`);else setMessage(`Convite: ${data.token}\nExpira em: ${new Date(data.expires_at).toLocaleString('pt-BR')}`);
  }catch(err){setMessage((err as Error).message);}finally{setBusy(false);}
 };
 const input='text-black p-2 rounded w-full';
 return <main className="min-h-screen bg-slate-950 text-white p-6 space-y-6 max-w-3xl mx-auto"><Link to="/hub">← Voltar</Link><h1 className="text-3xl font-bold">Contas por convite</h1><p>Piloto de cadastro. Acesso depende das permissões e da assinatura vinculadas à conta.</p>
 <details><summary>Primeiro acesso do administrador</summary><form className="space-y-3" onSubmit={e=>call(e,'setup-admin')}><label className="block">Código privado de configuração<input required name="token" className={input} pattern="[a-f0-9]{64}" autoComplete="off"/></label><label className="block">Defina sua nova senha<input required name="password" className={input} type="password" minLength={12} autoComplete="new-password"/></label><button disabled={busy} className="bg-green-700 p-2">Configurar meu acesso</button></form></details>
 {message && <p role="status" className="whitespace-pre-wrap break-all bg-slate-800 p-4">{message}</p>}
 <form onSubmit={e=>call(e,'accept')} className="space-y-3"><h2>Aceitar convite</h2><label className="block">Código do convite<input className={input} required name="token" pattern="[a-f0-9]{64}" autoComplete="off" /></label><label className="block">Nova senha (mínimo 12 caracteres)<input className={input} required name="password" type="password" minLength={12} autoComplete="new-password" /></label><button disabled={busy} className="bg-green-700 p-2">Criar minha conta</button></form>
 {!token?<form onSubmit={e=>call(e,'login')} className="space-y-3"><h2>Administração</h2><label className="block">Usuário<input required className={input} name="username" autoComplete="username" /></label><label className="block">Senha<input required className={input} name="password" type="password" autoComplete="current-password" /></label><button disabled={busy} className="bg-green-700 p-2">Entrar</button></form>:<>
 <button onClick={()=>{setToken('');setMessage('');}}>Sair da administração</button>
 <form onSubmit={e=>call(e,'organizations')} className="space-y-3"><h2>Criar espaço do treinador</h2><label className="block">Nome<input required className={input} name="name" maxLength={100} /></label><button disabled={busy} className="bg-green-700 p-2">Criar organização</button></form>
 <form onSubmit={e=>call(e,'invites')} className="space-y-3"><h2>Convidar ou redefinir acesso</h2><label className="block">Tipo de conta<select name="role" className={input} value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="coach">Treinador</option><option value="athlete">Aluno</option></select></label>{inviteRole==='athlete' && <label className="block">Identificador do aluno<input required className={input} name="athleteId"/></label>}<label className="block">Identificador da organização<input required className={input} name="organizationId"/></label><label className="block">Nome de usuário<input required className={input} name="username" pattern="[a-zA-Z0-9._@-]{3,100}"/></label><button disabled={busy} className="bg-green-700 p-2">Gerar convite</button></form></>}
 </main>;
}
