import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import type { UserWithPlan } from '../utils/plan';
export default function AccountSetup({onAuthenticated}:{onAuthenticated:(user:UserWithPlan)=>void}) {
 const [organizations,setOrganizations]=useState<{id:string;name:string}[]>([]);const [organizationId,setOrganizationId]=useState('');
 const [inviteRole,setInviteRole]=useState('coach');const [token,setToken]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!token)return;fetch('/api/accounts/organizations',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setOrganizations(d);}).catch(e=>setMessage(e.message));},[token]);
 const call=async(e:React.FormEvent<HTMLFormElement>,path:string)=>{
  e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;
  const body=Object.fromEntries(new FormData(form));
  try{const response=await fetch(`/api/accounts/${path}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const data=await response.json();if(!response.ok) throw Error(data.error);if(path==='login'){if(!data.platformAdmin) throw Error('Esta área é reservada à administração.');setToken(data.token);onAuthenticated(data);setMessage('Administração autenticada. Use Voltar para acessar seus atletas.');}else if(path==='setup-admin'){setMessage('Administração configurada. Entre com sua nova senha.');form.reset();}else if(path==='accept'){setMessage('Senha definida. Entre no aplicativo; o acesso depende da assinatura vinculada.');form.reset();}else if(path==='organizations'){setOrganizations(prev=>[...prev,{id:data.id,name:data.name}]);setOrganizationId(data.id);setMessage(`Organização criada: ${data.name}. Ela já está selecionada no convite.`);form.reset();}else setMessage(`Convite: ${data.token}\nExpira em: ${new Date(data.expires_at).toLocaleString('pt-BR')}`);
  }catch(err){setMessage((err as Error).message);}finally{setBusy(false);}
 };
 const input='admin-field w-full';
 return <main className="admin-page min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 space-y-6 max-w-3xl mx-auto"><Link to="/hub" className="text-green-400 font-semibold">← Voltar</Link><h1 className="text-3xl font-bold">Contas por convite</h1><p>Piloto de cadastro. Acesso depende das permissões e da assinatura vinculadas à conta.</p>
 <details><summary className="cursor-pointer rounded-lg border border-slate-500 bg-slate-800 p-4 font-semibold mb-3">Primeiro acesso do administrador</summary><form className="bg-slate-800 border border-slate-600 rounded-xl p-5 space-y-4" onSubmit={e=>call(e,'setup-admin')}><label className="block font-medium text-slate-100 space-y-2">Código privado de configuração<input required name="token" className={input} pattern="[a-f0-9]{64}" autoComplete="off"/></label><label className="block font-medium text-slate-100 space-y-2">Defina sua nova senha<input required name="password" className={input} type="password" minLength={12} autoComplete="new-password"/></label><button disabled={busy} className="bg-green-600 text-white rounded-lg font-semibold px-5 py-3 min-h-12 disabled:opacity-50">Configurar meu acesso</button></form></details>
 {message && <p role="status" className="whitespace-pre-wrap break-all bg-slate-800 p-4">{message}</p>}
 <form onSubmit={e=>call(e,'accept')} className="bg-slate-800 border border-slate-600 rounded-xl p-5 space-y-4"><h2 className="text-xl font-bold">Aceitar convite</h2><label className="block font-medium text-slate-100 space-y-2">Código do convite<input className={input} required name="token" pattern="[a-f0-9]{64}" autoComplete="off" /></label><label className="block font-medium text-slate-100 space-y-2">Nova senha (mínimo 12 caracteres)<input className={input} required name="password" type="password" minLength={12} autoComplete="new-password" /></label><button disabled={busy} className="bg-green-600 text-white rounded-lg font-semibold px-5 py-3 min-h-12 disabled:opacity-50">Criar minha conta</button></form>
 {!token?<form onSubmit={e=>call(e,'login')} className="bg-slate-800 border border-slate-600 rounded-xl p-5 space-y-4"><h2 className="text-xl font-bold">Administração</h2><label className="block font-medium text-slate-100 space-y-2">Usuário<input required className={input} name="username" autoComplete="username" /></label><label className="block font-medium text-slate-100 space-y-2">Senha<input required className={input} name="password" type="password" autoComplete="current-password" /></label><button disabled={busy} className="bg-green-600 text-white rounded-lg font-semibold px-5 py-3 min-h-12 disabled:opacity-50">Entrar</button></form>:<>
 <button className="border border-slate-400 rounded-lg px-5 py-3 font-semibold" onClick={()=>{setToken('');setMessage('');}}>Sair da administração</button>
 <form onSubmit={e=>call(e,'organizations')} className="bg-slate-800 border border-slate-600 rounded-xl p-5 space-y-4"><h2 className="text-xl font-bold">Criar espaço do treinador</h2><label className="block font-medium text-slate-100 space-y-2">Nome<input required className={input} name="name" maxLength={100} /></label><button disabled={busy} className="bg-green-600 text-white rounded-lg font-semibold px-5 py-3 min-h-12 disabled:opacity-50">Criar organização</button></form>
 <form onSubmit={e=>call(e,'invites')} className="bg-slate-800 border border-slate-600 rounded-xl p-5 space-y-4"><h2 className="text-xl font-bold">Convidar ou redefinir acesso</h2><label className="block font-medium text-slate-100 space-y-2">Tipo de conta<select name="role" className={input} value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="coach">Treinador</option><option value="athlete">Aluno</option></select></label>{inviteRole==='athlete' && <label className="block font-medium text-slate-100 space-y-2">Identificador do aluno<input required className={input} name="athleteId"/></label>}<label className="block font-medium text-slate-100 space-y-2">Organização<select required className={input} name="organizationId" value={organizationId} onChange={e=>setOrganizationId(e.target.value)}><option value="">Selecione a organização</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="block font-medium text-slate-100 space-y-2">Nome de usuário<input required className={input} name="username" placeholder="Ex.: treinador.teste" pattern="[a-zA-Z0-9._@-]{3,100}"/></label><button disabled={busy} className="bg-green-600 text-white rounded-lg font-semibold px-5 py-3 min-h-12 disabled:opacity-50">Gerar convite</button></form></>}
 </main>;
}
