import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import type { UserWithPlan } from '../utils/plan';
const sections:Record<string,string>={wellness:'Prontidão e bem-estar',workouts:'Treinos e prescrição',sessions:'Sessões externas',isometricStrength:'Força Q/I',generalStrength:'Força geral',imtp:'IMTP',cmj:'CMJ',dropJump:'Drop Jump',vo2max:'VO₂',speed:'Velocidade',bioimpedance:'Bioimpedância'};
const labels:Record<string,string>={name:'Nome',date:'Data',modality:'Modalidade',birth_date:'Nascimento',gender:'Sexo',goal:'Objetivo',position:'Posição',injury_history:'Histórico de lesões',competitive_level:'Nível competitivo',readiness_score:'Prontidão',fatigue:'Fadiga',sleep:'Sono',stress:'Estresse',soreness:'Dor muscular',mood:'Humor',rpe:'PSE',total_load:'Carga total',duration_minutes:'Duração (min)',status:'Status',feedback:'Feedback',trainer_notes:'Observações do treinador',phase:'Fase',weight:'Peso',height:'Altura',observations:'Observações',exercises:'Exercícios',performed_sets:'Séries realizadas',sets:'Séries',reps:'Repetições',load:'Carga',rest:'Intervalo',notes:'Observações',exercise_name:'Exercício',sleep_quality:'Qualidade do sono',hrv:'VFC',peak_force:'Força de pico',relative_peak_force:'Força relativa',time_to_peak_force:'Tempo até o pico',mean_force:'Força média',impulse:'Impulso'};
const hidden=new Set(['id','athlete_id','workout_id','exercise_id','created_at','updated_at']);
function Fields({value}:{value:any}){
 if(value==null)return null;
 if(typeof value!=='object')return <span className="whitespace-pre-wrap break-words">{typeof value==='boolean'?(value?'Sim':'Não'):String(value)}</span>;
 if(Array.isArray(value))return <div className="space-y-3">{value.length?value.map((item,i)=><div key={i} className="border border-slate-300 rounded p-3"><Fields value={item}/></div>):<span>Sem registros</span>}</div>;
 return <dl className="grid grid-cols-1 sm:grid-cols-2 gap-3">{Object.entries(value).filter(([key,v])=>!hidden.has(key)&&v!=null&&v!=='').map(([key,v])=><div key={key} className={typeof v==='object'?'sm:col-span-2':''}><dt className="font-semibold text-slate-700">{labels[key] || key.replace(/_/g,' ')}</dt><dd className="text-slate-950"><Fields value={v}/></dd></div>)}</dl>;
}
export default function Supervisor({user}:{user:UserWithPlan}){
 const [organizations,setOrganizations]=useState<any[]>([]),[organization,setOrganization]=useState(''),[athletes,setAthletes]=useState<any[]>([]),[athlete,setAthlete]=useState(''),[kind,setKind]=useState('wellness'),[page,setPage]=useState(0),[detail,setDetail]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
 const version=useRef(0);
 const api=async(path:string,init:RequestInit={})=>{const response=await fetch('/api/accounts/supervisor/'+path,{...init,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${user.token}`}});const data=await response.json();if(response.status===401)window.dispatchEvent(new Event('lb:session-invalid'));if(!response.ok)throw Error(data.error || 'Falha ao carregar.');return data;};
 const refresh=async()=>setOrganizations(await api('organizations'));
 useEffect(()=>{let alive=true;api('organizations').then(data=>{if(alive)setOrganizations(data);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[user.token]);
 useEffect(()=>{let alive=true;setAthletes([]);setAthlete('');setDetail(null);setPage(0);setError('');if(organization){setLoading(true);api(`organizations/${organization}/athletes`).then(data=>{if(alive)setAthletes(data);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});}else setLoading(false);return()=>{alive=false;};},[organization,user.token]);
 useEffect(()=>{const current=++version.current;setDetail(null);setError('');if(!organization||!athlete)return;setLoading(true);api(`organizations/${organization}/athletes/${encodeURIComponent(athlete)}?kind=${kind}&page=${page}`).then(data=>{if(version.current===current)setDetail(data);}).catch(e=>{if(version.current===current)setError(e.message);}).finally(()=>{if(version.current===current)setLoading(false);});return()=>{version.current++;};},[organization,athlete,kind,page,user.token]);
 const link=async(org:any)=>{setBusy(true);setError('');try{await api(`organizations/${org.id}/link`,{method:'PUT',body:JSON.stringify({enabled:!org.linked})});if(org.linked&&organization===org.id){version.current++;setOrganization('');setDetail(null);setAthletes([]);}await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const field='admin-field w-full';
 return <main className="admin-page min-h-screen bg-slate-950 text-slate-100 p-4 sm:p-6 space-y-6 max-w-6xl mx-auto"><Link to="/hub" className="text-green-400 font-semibold">← Meus atletas</Link><h1 className="text-3xl font-bold">Supervisão de treinadores</h1><p>Acompanhe as organizações vinculadas à sua supervisão. Consulta de atletas, avaliações e treinos; as alterações continuam com o treinador responsável.</p>{error&&<p role="alert" className="bg-red-100 text-red-900 p-4 rounded">{error}</p>}
 <details className="bg-slate-800 p-5 rounded-xl border border-slate-600"><summary className="cursor-pointer font-semibold text-xl">Organizações e vínculos</summary><div className="space-y-3 mt-4">{organizations.map(org=><div key={org.id} className="flex flex-wrap gap-3 items-center justify-between border-b border-slate-600 pb-3"><div><strong>{org.name}</strong><p>{org.coaches.join(', ') || 'Sem treinador cadastrado'} · {org.athlete_count} atleta(s)</p><p>{org.linked?'Supervisão vinculada':'Sem supervisão'}</p></div><button disabled={busy} onClick={()=>link(org)} className="bg-green-600 text-white px-5 py-3 rounded font-semibold disabled:opacity-50">{org.linked?'Desvincular':'Vincular à supervisão'}</button></div>)}</div></details>
 <div className="grid sm:grid-cols-3 gap-4"><label>Organização / Treinador<select value={organization} onChange={e=>setOrganization(e.target.value)} className={field}><option value="">Selecione uma organização vinculada</option>{organizations.filter(o=>o.linked).map(o=><option key={o.id} value={o.id}>{o.name} — {o.coaches.join(', ')}</option>)}</select></label><label>Atleta<select value={athlete} onChange={e=>{setAthlete(e.target.value);setPage(0);}} className={field} disabled={!organization}><option value="">Selecione o atleta</option>{athletes.map(a=><option key={a.id} value={a.id}>{a.name} — {a.modality}</option>)}</select></label><label>Conteúdo<select value={kind} onChange={e=>{setKind(e.target.value);setPage(0);}} className={field}>{Object.entries(sections).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label></div>
 {loading&&<p role="status">Carregando dados…</p>}{organization&&!loading&&!athletes.length&&!error&&<p>Esta organização ainda não possui atletas cadastrados.</p>}
 {detail&&<><details className="bg-white text-slate-900 p-5 rounded-xl"><summary className="font-bold text-xl cursor-pointer">{detail.athlete.name} — Perfil</summary><div className="mt-4"><Fields value={detail.athlete}/></div></details><h2 className="text-xl font-semibold">{sections[kind]}</h2>{!detail.records.length&&<p>Sem registros neste conteúdo.</p>}{detail.records.map((record:any)=><article key={record.id} className="bg-white text-slate-900 p-5 rounded-xl border border-slate-300"><Fields value={record}/></article>)}<div className="flex items-center gap-4"><button disabled={!page||loading} onClick={()=>setPage(p=>p-1)} className="bg-green-600 px-4 py-3 rounded disabled:opacity-40">Anterior</button><span>Página {page+1}</span><button disabled={!detail.hasMore||loading} onClick={()=>setPage(p=>p+1)} className="bg-green-600 px-4 py-3 rounded disabled:opacity-40">Próxima</button></div></>}
 </main>;
}
