-- DRAFT ONLY — NÃO APLICAR EM PRODUÇÃO
-- Método LB Performance v1.0
-- Compatível com o banco atual, que usa athletes.id como TEXT.
-- O schema privado evita expor o novo núcleo diretamente ao Data API
-- enquanto a aplicação continuar usando JWT próprio no Express.

create schema if not exists lb_core;

create table if not exists lb_core.assessment_sessions (
  id text primary key,
  athlete_id text not null references public.athletes(id) on delete cascade,
  test_type text not null,
  assessed_at timestamptz not null default now(),
  protocol_version text not null,
  quality_flag text not null check (quality_flag in ('VALID','CAUTION','NON_COMPARABLE','REPEAT')),
  comparable_to_baseline boolean not null default false,
  device text,
  operator_name text,
  context jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists lb_core.assessment_metrics (
  id text primary key,
  session_id text not null references lb_core.assessment_sessions(id) on delete cascade,
  metric_code text not null,
  value_numeric numeric,
  value_text text,
  unit text,
  trial_no integer,
  is_valid boolean not null default true,
  created_at timestamptz not null default now(),
  check (value_numeric is not null or value_text is not null)
);

create table if not exists lb_core.interpretations (
  id text primary key,
  session_id text not null references lb_core.assessment_sessions(id) on delete cascade,
  comparator text,
  noise_reference text,
  context_text text,
  convergence text,
  confidence text not null check (confidence in ('HIGH','MODERATE','LOW')),
  main_limitation text,
  missing_data text,
  conclusion text,
  created_at timestamptz not null default now(),
  check (confidence <> 'LOW' or nullif(trim(main_limitation), '') is not null)
);

create table if not exists lb_core.decisions (
  id text primary key,
  athlete_id text not null references public.athletes(id) on delete cascade,
  session_id text references lb_core.assessment_sessions(id) on delete set null,
  decision_class text not null check (decision_class in ('MAINTAIN','MONITOR','INVESTIGATE','INTERVENE','REFER_STOP')),
  priority text,
  rationale text not null,
  cost_of_acting text,
  cost_of_not_acting text,
  review_trigger text not null,
  alternative_discarded text,
  created_at timestamptz not null default now()
);

create table if not exists lb_core.prescriptions (
  id text primary key,
  athlete_id text not null references public.athletes(id) on delete cascade,
  decision_id text references lb_core.decisions(id) on delete set null,
  target_capacity text not null,
  hypothesis text not null,
  method text,
  dose text,
  quality_criterion text,
  progression_criterion text,
  created_at timestamptz not null default now()
);

create table if not exists lb_core.monitoring_entries (
  id text primary key,
  athlete_id text not null references public.athletes(id) on delete cascade,
  prescription_id text references lb_core.prescriptions(id) on delete set null,
  observed_at timestamptz not null default now(),
  load_data jsonb not null default '{}'::jsonb,
  state_data jsonb not null default '{}'::jsonb,
  response_data jsonb not null default '{}'::jsonb,
  context_data jsonb not null default '{}'::jsonb,
  action_taken text,
  created_at timestamptz not null default now()
);

create table if not exists lb_core.reassessments (
  id text primary key,
  athlete_id text not null references public.athletes(id) on delete cascade,
  original_session_id text references lb_core.assessment_sessions(id) on delete set null,
  reassessment_session_id text references lb_core.assessment_sessions(id) on delete set null,
  change_status text not null check (change_status in ('OBSERVED','DETECTABLE','IMPORTANT','INCONCLUSIVE')),
  observed_change text,
  relevance text,
  hypothesis_supported boolean,
  next_decision text,
  created_at timestamptz not null default now()
);

create table if not exists lb_core.transfer_evidence (
  id text primary key,
  athlete_id text not null references public.athletes(id) on delete cascade,
  decision_id text references lb_core.decisions(id) on delete set null,
  status text not null check (status in ('SUPPORT','PARTIAL','SUSTAINED','INCONCLUSIVE')),
  capacity_evidence text,
  bridge_task_evidence text,
  sport_action_evidence text,
  competition_evidence text,
  limitation text,
  created_at timestamptz not null default now()
);

create table if not exists lb_core.audit_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_id text,
  athlete_id text,
  entity_type text,
  entity_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists lb_assessment_sessions_athlete_idx
  on lb_core.assessment_sessions (athlete_id, assessed_at desc);

create index if not exists lb_decisions_athlete_idx
  on lb_core.decisions (athlete_id, created_at desc);

create index if not exists lb_monitoring_athlete_idx
  on lb_core.monitoring_entries (athlete_id, observed_at desc);

-- Antes de transformar este rascunho em migration:
-- 1. criar staging;
-- 2. definir o modelo definitivo de autenticação;
-- 3. decidir se o Data API deverá acessar lb_core;
-- 4. executar advisors;
-- 5. gerar migration formal pela ferramenta/CLI apropriada.
